apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-lgtm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/evoila-bosnia/envision-demo.git
    targetRevision: main
    path: apps/otel-lgtm/overlays/envision
  destination:
    server: https://kubernetes.default.svc
    namespace: envision-demo
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
